### ISSUE TITLE
[public/pages] Add styles folder and first stylesheet

### ISSUE THREAD

**Issue by codeTrackLift** [codepharm/dkfront#17]
Create folder `styles` under `public/pages`

Create stylesheet `global.css` and link into your `index.html`

```
*, *:after, *:before {
  box-sizing: border-box;
}

html {
  overflow-x: hidden;
}
```

**Comment by nettle790** [comment]
can I give this issue a try since its open. I am a beginner

**Comment by IsthisSid** [comment]
Hi @nettle790 Welcome! I apologize I haven't looked at this project for a while and we have to close some of the issues in this repo. 

However, please check out our playground repo! This is a great place for anyone who wants to collaborate and contribute (beginners and seniors). I'll meet you there!

**Comment by nettle790** [comment]
ok
