### ISSUE TITLE
Fill Services Page and change services links and text to "Training Grounds" instead

### ISSUE THREAD

**Issue by IsthisSid** [codepharm/dkfront#51]
- Pull down the latest copy of main
- Run nvm use
- Check out a new branch to fill out the services page and replace the lorem ipsum
- Services will be split into categories: beginner, intermediate, advanced
- Rename all 'Services' to 'Training Grounds' per client request

**Comment by codeTrackLift** [comment]
Do these need to be separate pages?  Or can you list them in different rows on the same page?

**Comment by IsthisSid** [comment]
Different rows same page

**Comment by codeTrackLift** [comment]
Can you handle this with the component rows?

**Comment by IsthisSid** [comment]
Sure, I labeled this as low priority. I need more clarity from him on the services then work on it.
